-- Generated from the final D1 schema for Supabase PostgreSQL.
-- Run after 0001_auth_storage.sql. Re-running is safe for tables/indexes.

CREATE TABLE IF NOT EXISTS customers (
	id bigint generated by default as identity primary key NOT NULL,
	email text NOT NULL,
	first_name text NOT NULL,
	last_name text NOT NULL,
	address text NOT NULL,
	city text NOT NULL,
	pin_code text NOT NULL,
	created_at bigint DEFAULT (extract(epoch from now())::bigint) NOT NULL,
	updated_at bigint DEFAULT (extract(epoch from now())::bigint) NOT NULL
, phone text DEFAULT '' NOT NULL, auth_provider text DEFAULT 'siwc' NOT NULL, referral_code text DEFAULT '' NOT NULL, referred_by_customer_id bigint, first_paid_at bigint, status text DEFAULT 'active' NOT NULL, auth_user_id text);

CREATE TABLE IF NOT EXISTS newsletter_subscribers (
	id bigint generated by default as identity primary key NOT NULL,
	email text NOT NULL,
	subscribed_at bigint DEFAULT (extract(epoch from now())::bigint) NOT NULL
);

CREATE TABLE IF NOT EXISTS products (
  id bigint generated by default as identity primary key,
  slug TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  price bigint NOT NULL,
  compare_at_price bigint,
  category TEXT NOT NULL,
  color TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'draft',
  sku TEXT NOT NULL UNIQUE,
  collection_ids TEXT NOT NULL DEFAULT '[]',
  created_at bigint NOT NULL DEFAULT (extract(epoch from now())::bigint),
  updated_at bigint NOT NULL DEFAULT (extract(epoch from now())::bigint)
, short_description TEXT NOT NULL DEFAULT '', featured bigint NOT NULL DEFAULT 0, new_arrival bigint NOT NULL DEFAULT 0, audience TEXT NOT NULL DEFAULT 'unisex', product_type TEXT NOT NULL DEFAULT 'apparel', tags TEXT NOT NULL DEFAULT '[]', seo_title TEXT NOT NULL DEFAULT '', seo_description TEXT NOT NULL DEFAULT '', cost_price bigint, tax_status TEXT NOT NULL DEFAULT 'taxable', hidden_at bigint, hidden_reason TEXT, hidden_by TEXT, archived_at bigint, archived_reason TEXT, archived_by TEXT, deleted_at bigint);

CREATE TABLE IF NOT EXISTS product_variants (
  id bigint generated by default as identity primary key,
  product_id bigint NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  size TEXT NOT NULL,
  color TEXT NOT NULL,
  sku TEXT NOT NULL UNIQUE,
  stock bigint NOT NULL DEFAULT 0,
  low_stock_threshold bigint NOT NULL DEFAULT 5, reserved_stock bigint NOT NULL DEFAULT 0, price bigint, active bigint NOT NULL DEFAULT 1,
  UNIQUE(product_id, size, color)
);

CREATE TABLE IF NOT EXISTS product_images (
  id bigint generated by default as identity primary key,
  product_id bigint NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  url TEXT NOT NULL,
  alt_text TEXT NOT NULL DEFAULT '',
  sort_order bigint NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS orders (
	id bigint generated by default as identity primary key NOT NULL,
	customer_id bigint NOT NULL,
	total_amount bigint NOT NULL,
	status text DEFAULT 'pending' NOT NULL,
	created_at bigint DEFAULT (extract(epoch from now())::bigint) NOT NULL, wallet_amount bigint DEFAULT 0 NOT NULL, payable_amount bigint DEFAULT 0 NOT NULL, payment_reference text, paid_at bigint, cancelled_at bigint, refunded_at bigint, shipping_status TEXT NOT NULL DEFAULT 'unfulfilled', tracking_id TEXT, payment_status TEXT NOT NULL DEFAULT 'pending', internal_status TEXT NOT NULL DEFAULT 'open', checkout_key text, subtotal_amount bigint DEFAULT 0 NOT NULL, discount_amount bigint DEFAULT 0 NOT NULL, shipping_amount bigint DEFAULT 0 NOT NULL, shipping_address TEXT NOT NULL DEFAULT '{}', payment_method TEXT NOT NULL DEFAULT 'cod', coupon_code TEXT, courier TEXT, confirmed_at bigint, confirmed_by TEXT, shipped_at bigint, delivered_at bigint, estimated_delivery_at bigint, tracking_url TEXT, customer_message TEXT, cancellation_reason TEXT, inventory_restored_at bigint, refund_status TEXT NOT NULL DEFAULT 'none',
	FOREIGN KEY (customer_id) REFERENCES customers(id) ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS order_items (
	id bigint generated by default as identity primary key NOT NULL,
	order_id bigint NOT NULL,
	product_slug text NOT NULL,
	product_name text NOT NULL,
	unit_price bigint NOT NULL,
	quantity bigint NOT NULL,
	size text NOT NULL, color TEXT NOT NULL DEFAULT '', variant_id bigint REFERENCES product_variants(id),
	FOREIGN KEY (order_id) REFERENCES orders(id) ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS addresses (
	id bigint generated by default as identity primary key NOT NULL,
	customer_id bigint NOT NULL,
	label text DEFAULT 'Home' NOT NULL,
	first_name text NOT NULL,
	last_name text NOT NULL,
	phone text NOT NULL,
	line1 text NOT NULL,
	line2 text DEFAULT '' NOT NULL,
	city text NOT NULL,
	state text NOT NULL,
	pin_code text NOT NULL,
	is_default bigint DEFAULT 0 NOT NULL,
	created_at bigint DEFAULT (extract(epoch from now())::bigint) NOT NULL,
	updated_at bigint DEFAULT (extract(epoch from now())::bigint) NOT NULL,
	FOREIGN KEY (customer_id) REFERENCES customers(id) ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS referral_config (
	id bigint primary key,
	reward_amount bigint DEFAULT 10000 NOT NULL,
	auto_approve bigint DEFAULT 1 NOT NULL,
	enabled bigint DEFAULT 1 NOT NULL,
	updated_at bigint DEFAULT (extract(epoch from now())::bigint) NOT NULL
);

CREATE TABLE IF NOT EXISTS referrals (
	id bigint generated by default as identity primary key NOT NULL,
	referrer_customer_id bigint NOT NULL,
	referred_customer_id bigint NOT NULL,
	qualifying_order_id bigint,
	reward_amount bigint NOT NULL,
	status text DEFAULT 'registered' NOT NULL,
	fraud_reason text,
	created_at bigint DEFAULT (extract(epoch from now())::bigint) NOT NULL,
	approved_at bigint,
	reversed_at bigint,
	FOREIGN KEY (referrer_customer_id) REFERENCES customers(id) ON UPDATE NO ACTION ON DELETE NO ACTION,
	FOREIGN KEY (referred_customer_id) REFERENCES customers(id) ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS wallet_ledger (
	id bigint generated by default as identity primary key NOT NULL,
	customer_id bigint NOT NULL,
	referral_id bigint,
	order_id bigint,
	amount bigint NOT NULL,
	type text NOT NULL,
	status text NOT NULL,
	note text NOT NULL,
	idempotency_key text NOT NULL,
	created_at bigint DEFAULT (extract(epoch from now())::bigint) NOT NULL,
	FOREIGN KEY (customer_id) REFERENCES customers(id) ON UPDATE NO ACTION ON DELETE NO ACTION,
	FOREIGN KEY (referral_id) REFERENCES referrals(id) ON UPDATE NO ACTION ON DELETE NO ACTION,
	FOREIGN KEY (order_id) REFERENCES orders(id) ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS wishlists (
	id bigint generated by default as identity primary key NOT NULL,
	customer_id bigint NOT NULL,
	product_slug text NOT NULL,
	created_at bigint DEFAULT (extract(epoch from now())::bigint) NOT NULL,
	FOREIGN KEY (customer_id) REFERENCES customers(id) ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS inventory_movements (
  id bigint generated by default as identity primary key,
  variant_id bigint NOT NULL REFERENCES product_variants(id),
  delta bigint NOT NULL,
  reason TEXT NOT NULL,
  admin_email TEXT NOT NULL,
  created_at bigint NOT NULL DEFAULT (extract(epoch from now())::bigint)
);

CREATE TABLE IF NOT EXISTS categories (
  id bigint generated by default as identity primary key,
  name TEXT NOT NULL UNIQUE,
  slug TEXT NOT NULL UNIQUE,
  status TEXT NOT NULL DEFAULT 'active',
  sort_order bigint NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS collections (
  id bigint generated by default as identity primary key,
  name TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  description TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'draft',
  image_url TEXT,
  created_at bigint NOT NULL DEFAULT (extract(epoch from now())::bigint),
  updated_at bigint NOT NULL DEFAULT (extract(epoch from now())::bigint)
, audience TEXT NOT NULL DEFAULT 'unisex', featured bigint NOT NULL DEFAULT 0);

CREATE TABLE IF NOT EXISTS returns (
  id bigint generated by default as identity primary key,
  order_id bigint NOT NULL REFERENCES orders(id),
  customer_id bigint NOT NULL REFERENCES customers(id),
  reason TEXT NOT NULL,
  image_urls TEXT NOT NULL DEFAULT '[]',
  decision_status TEXT NOT NULL DEFAULT 'requested',
  pickup_status TEXT NOT NULL DEFAULT 'pending',
  refund_status TEXT NOT NULL DEFAULT 'pending',
  admin_note TEXT NOT NULL DEFAULT '',
  created_at bigint NOT NULL DEFAULT (extract(epoch from now())::bigint),
  updated_at bigint NOT NULL DEFAULT (extract(epoch from now())::bigint)
);

CREATE TABLE IF NOT EXISTS discounts (
  id bigint generated by default as identity primary key,
  code TEXT NOT NULL UNIQUE,
  type TEXT NOT NULL,
  value bigint NOT NULL,
  starts_at bigint,
  ends_at bigint,
  usage_limit bigint,
  usage_count bigint NOT NULL DEFAULT 0,
  minimum_order bigint NOT NULL DEFAULT 0,
  target_type TEXT NOT NULL DEFAULT 'all',
  target_ids TEXT NOT NULL DEFAULT '[]',
  status TEXT NOT NULL DEFAULT 'draft',
  created_at bigint NOT NULL DEFAULT (extract(epoch from now())::bigint)
);

CREATE TABLE IF NOT EXISTS payouts (
  id bigint generated by default as identity primary key,
  customer_id bigint NOT NULL REFERENCES customers(id),
  amount bigint NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  bank_reference TEXT,
  note TEXT NOT NULL DEFAULT '',
  created_at bigint NOT NULL DEFAULT (extract(epoch from now())::bigint),
  processed_at bigint
);

CREATE TABLE IF NOT EXISTS content_sections (
  id bigint generated by default as identity primary key,
  section_key TEXT NOT NULL UNIQUE,
  section_type TEXT NOT NULL,
  title TEXT NOT NULL DEFAULT '',
  subtitle TEXT NOT NULL DEFAULT '',
  body TEXT NOT NULL DEFAULT '',
  image_url TEXT,
  cta_label TEXT,
  cta_url TEXT,
  sort_order bigint NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'draft',
  published_at bigint,
  updated_at bigint NOT NULL DEFAULT (extract(epoch from now())::bigint)
);

CREATE TABLE IF NOT EXISTS store_settings (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL,
  updated_at bigint NOT NULL DEFAULT (extract(epoch from now())::bigint)
);

CREATE TABLE IF NOT EXISTS order_notes (
  id bigint generated by default as identity primary key,
  order_id bigint NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  note TEXT NOT NULL,
  admin_email TEXT NOT NULL,
  created_at bigint NOT NULL DEFAULT (extract(epoch from now())::bigint)
);

CREATE TABLE IF NOT EXISTS audit_logs (
  id bigint generated by default as identity primary key,
  admin_email TEXT NOT NULL,
  action TEXT NOT NULL,
  resource TEXT NOT NULL,
  resource_id TEXT,
  detail TEXT NOT NULL DEFAULT '{}',
  created_at bigint NOT NULL DEFAULT (extract(epoch from now())::bigint)
);

CREATE TABLE IF NOT EXISTS admin_roles (
  email TEXT PRIMARY KEY,
  role TEXT NOT NULL DEFAULT 'viewer',
  permissions TEXT NOT NULL DEFAULT '[]',
  status TEXT NOT NULL DEFAULT 'active',
  updated_at bigint NOT NULL DEFAULT (extract(epoch from now())::bigint)
, auth_user_id text);

CREATE TABLE IF NOT EXISTS carts (
  id bigint generated by default as identity primary key,
  customer_id bigint NOT NULL UNIQUE REFERENCES customers(id),
  updated_at bigint NOT NULL DEFAULT (extract(epoch from now())::bigint)
);

CREATE TABLE IF NOT EXISTS cart_items (
  id bigint generated by default as identity primary key,
  cart_id bigint NOT NULL REFERENCES carts(id) ON DELETE CASCADE,
  variant_id bigint NOT NULL REFERENCES product_variants(id),
  quantity bigint NOT NULL CHECK (quantity > 0),
  created_at bigint NOT NULL DEFAULT (extract(epoch from now())::bigint),
  UNIQUE(cart_id, variant_id)
);

CREATE TABLE IF NOT EXISTS payments (
  id bigint generated by default as identity primary key,
  order_id bigint NOT NULL REFERENCES orders(id),
  provider TEXT NOT NULL,
  gateway_order_id TEXT,
  gateway_payment_id TEXT,
  amount bigint NOT NULL,
  currency TEXT NOT NULL DEFAULT 'INR',
  status TEXT NOT NULL DEFAULT 'pending',
  failure_reason TEXT,
  created_at bigint NOT NULL DEFAULT (extract(epoch from now())::bigint),
  updated_at bigint NOT NULL DEFAULT (extract(epoch from now())::bigint)
);

CREATE TABLE IF NOT EXISTS coupons (
  id bigint generated by default as identity primary key,
  code TEXT NOT NULL UNIQUE,
  type TEXT NOT NULL CHECK (type IN ('percentage','fixed')),
  value bigint NOT NULL,
  minimum_order bigint NOT NULL DEFAULT 0,
  maximum_discount bigint,
  starts_at bigint,
  ends_at bigint,
  usage_limit bigint,
  per_customer_limit bigint NOT NULL DEFAULT 1,
  usage_count bigint NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'draft'
, description TEXT NOT NULL DEFAULT '', first_order_only bigint NOT NULL DEFAULT 0, payment_methods TEXT NOT NULL DEFAULT '[]');

CREATE TABLE IF NOT EXISTS coupon_usages (
  id bigint generated by default as identity primary key,
  coupon_id bigint NOT NULL REFERENCES coupons(id),
  customer_id bigint NOT NULL REFERENCES customers(id),
  order_id bigint NOT NULL REFERENCES orders(id),
  discount_amount bigint NOT NULL,
  created_at bigint NOT NULL DEFAULT (extract(epoch from now())::bigint)
);

CREATE TABLE IF NOT EXISTS order_status_history (
  id bigint generated by default as identity primary key,
  order_id bigint NOT NULL REFERENCES orders(id),
  status TEXT NOT NULL,
  note TEXT NOT NULL DEFAULT '',
  actor_email TEXT,
  created_at bigint NOT NULL DEFAULT (extract(epoch from now())::bigint)
);

CREATE TABLE IF NOT EXISTS reviews (
  id bigint generated by default as identity primary key,
  customer_id bigint NOT NULL REFERENCES customers(id),
  product_id bigint NOT NULL REFERENCES products(id),
  rating bigint NOT NULL CHECK (rating BETWEEN 1 AND 5),
  body TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'pending',
  created_at bigint NOT NULL DEFAULT (extract(epoch from now())::bigint)
);

CREATE TABLE IF NOT EXISTS customer_notes (
  id bigint generated by default as identity primary key,
  customer_id bigint NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
  note TEXT NOT NULL,
  admin_email TEXT NOT NULL,
  created_at bigint NOT NULL DEFAULT (extract(epoch from now())::bigint)
);

CREATE TABLE IF NOT EXISTS order_timeline (
  id bigint generated by default as identity primary key,
  order_id bigint NOT NULL REFERENCES orders(id),
  event_type TEXT NOT NULL,
  public_title TEXT NOT NULL,
  public_description TEXT NOT NULL DEFAULT '',
  internal_description TEXT NOT NULL DEFAULT '',
  actor_email TEXT,
  created_at bigint NOT NULL DEFAULT (extract(epoch from now())::bigint)
);

CREATE UNIQUE INDEX IF NOT EXISTS customers_email_unique ON customers (email);
CREATE UNIQUE INDEX IF NOT EXISTS newsletter_subscribers_email_idx ON newsletter_subscribers (email);
CREATE INDEX IF NOT EXISTS addresses_customer_idx ON addresses (customer_id);
CREATE UNIQUE INDEX IF NOT EXISTS referrals_referred_customer_idx ON referrals (referred_customer_id);
CREATE INDEX IF NOT EXISTS referrals_referrer_idx ON referrals (referrer_customer_id);
CREATE UNIQUE INDEX IF NOT EXISTS wallet_ledger_idempotency_key_unique ON wallet_ledger (idempotency_key);
CREATE INDEX IF NOT EXISTS wallet_customer_idx ON wallet_ledger (customer_id);
CREATE UNIQUE INDEX IF NOT EXISTS wishlist_customer_product_idx ON wishlists (customer_id,product_slug);
CREATE UNIQUE INDEX IF NOT EXISTS customers_referral_code_unique ON customers (referral_code);
CREATE INDEX IF NOT EXISTS products_status_idx ON products(status);
CREATE INDEX IF NOT EXISTS variants_product_idx ON product_variants(product_id);
CREATE INDEX IF NOT EXISTS inventory_movements_variant_idx ON inventory_movements(variant_id);
CREATE INDEX IF NOT EXISTS returns_status_idx ON returns(decision_status);
CREATE INDEX IF NOT EXISTS discounts_code_idx ON discounts(code);
CREATE INDEX IF NOT EXISTS audit_resource_idx ON audit_logs(resource, created_at);
CREATE UNIQUE INDEX IF NOT EXISTS orders_checkout_key_unique ON orders (checkout_key);
CREATE INDEX IF NOT EXISTS carts_customer_idx ON carts(customer_id);
CREATE INDEX IF NOT EXISTS cart_items_cart_idx ON cart_items(cart_id);
CREATE INDEX IF NOT EXISTS payments_order_idx ON payments(order_id);
CREATE INDEX IF NOT EXISTS coupon_usage_customer_idx ON coupon_usages(coupon_id, customer_id);
CREATE INDEX IF NOT EXISTS order_history_order_idx ON order_status_history(order_id, created_at);
CREATE INDEX IF NOT EXISTS reviews_product_idx ON reviews(product_id, status);
CREATE INDEX IF NOT EXISTS products_catalog_idx ON products(status, category);
CREATE UNIQUE INDEX IF NOT EXISTS customers_auth_user_id_unique ON customers (auth_user_id) WHERE auth_user_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS admin_roles_auth_user_id_unique ON admin_roles (auth_user_id) WHERE auth_user_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS customer_notes_customer_idx ON customer_notes(customer_id,created_at DESC);
CREATE INDEX IF NOT EXISTS order_timeline_order_idx ON order_timeline(order_id,created_at);

-- Commerce is accessed only by the trusted Next.js server through DATABASE_URL.
-- Enabling RLS without public policies blocks anon/authenticated Data API access.
alter table public.customers enable row level security;
alter table public.newsletter_subscribers enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.addresses enable row level security;
alter table public.referral_config enable row level security;
alter table public.referrals enable row level security;
alter table public.wallet_ledger enable row level security;
alter table public.wishlists enable row level security;
alter table public.products enable row level security;
alter table public.product_variants enable row level security;
alter table public.product_images enable row level security;
alter table public.inventory_movements enable row level security;
alter table public.categories enable row level security;
alter table public.collections enable row level security;
alter table public.returns enable row level security;
alter table public.discounts enable row level security;
alter table public.payouts enable row level security;
alter table public.content_sections enable row level security;
alter table public.store_settings enable row level security;
alter table public.order_notes enable row level security;
alter table public.audit_logs enable row level security;
alter table public.admin_roles enable row level security;
alter table public.carts enable row level security;
alter table public.cart_items enable row level security;
alter table public.payments enable row level security;
alter table public.coupons enable row level security;
alter table public.coupon_usages enable row level security;
alter table public.order_status_history enable row level security;
alter table public.reviews enable row level security;
alter table public.customer_notes enable row level security;
alter table public.order_timeline enable row level security;
