-- Name + phone member accounts and admin-visible sign-in activity.
-- Run once in Supabase Dashboard > SQL Editor, after 0001_auth_storage.sql
-- and 0002_commerce.sql.

alter table public.customers add column if not exists last_login_at bigint;

create table if not exists public.customer_login_events (
  id bigint generated by default as identity primary key,
  customer_id bigint not null references public.customers(id) on delete cascade,
  auth_user_id text not null,
  phone text not null,
  created_at bigint not null default (extract(epoch from now())::bigint)
);

-- This migration originally used a UUID linked to auth.users for phone OTP.
-- Name + phone members use a signed app session instead, so keep the log field
-- as text and make this safe to run for projects that used the earlier draft.
alter table public.customer_login_events
  drop constraint if exists customer_login_events_auth_user_id_fkey;
alter table public.customer_login_events
  alter column auth_user_id type text using auth_user_id::text;

create index if not exists customer_login_events_customer_idx
  on public.customer_login_events(customer_id, created_at desc);

alter table public.customer_login_events enable row level security;

-- Phone-only Supabase users do not have an email. Keep an internal, unique
-- placeholder only for compatibility with the legacy commerce email column;
-- customers never see it and phone remains their actual contact identifier.
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = '' as $$
declare
  profile_email text;
begin
  profile_email := coalesce(
    new.email,
    'phone-' || regexp_replace(coalesce(new.phone, new.id::text), '[^0-9]', '', 'g') || '@members.invalid'
  );

  insert into public.profiles (id, email, full_name, phone)
  values (
    new.id,
    profile_email,
    coalesce(new.raw_user_meta_data ->> 'full_name', ''),
    coalesce(new.phone, '')
  )
  on conflict (id) do update set
    email = excluded.email,
    full_name = excluded.full_name,
    phone = excluded.phone,
    updated_at = now();
  return new;
end;
$$;
