-- P&R numbered editions and the private Unique Finds archive.
-- Existing catalogue rows stay valid: edition_number is nullable until an
-- administrator assigns a number through the product editor.

ALTER TABLE products ADD COLUMN IF NOT EXISTS edition_number bigint;
ALTER TABLE products ADD COLUMN IF NOT EXISTS is_unique_find bigint NOT NULL DEFAULT 0;
ALTER TABLE products ADD COLUMN IF NOT EXISTS lifetime_production_cap bigint;
ALTER TABLE products ADD COLUMN IF NOT EXISTS total_units_created bigint NOT NULL DEFAULT 0;
ALTER TABLE products ADD COLUMN IF NOT EXISTS unique_find_status text NOT NULL DEFAULT 'available';
ALTER TABLE products ADD COLUMN IF NOT EXISTS archive_date bigint;
ALTER TABLE products ADD COLUMN IF NOT EXISTS archive_note text NOT NULL DEFAULT '';
ALTER TABLE products ADD COLUMN IF NOT EXISTS keep_visible_after_sellout bigint NOT NULL DEFAULT 1;
ALTER TABLE products ADD COLUMN IF NOT EXISTS unique_release_at bigint;

CREATE UNIQUE INDEX IF NOT EXISTS products_edition_number_unique
  ON products(edition_number) WHERE edition_number IS NOT NULL;
CREATE INDEX IF NOT EXISTS products_unique_finds_idx
  ON products(is_unique_find, status, unique_find_status);

ALTER TABLE order_items ADD COLUMN IF NOT EXISTS edition_number bigint;
ALTER TABLE order_items ADD COLUMN IF NOT EXISTS is_unique_find bigint NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS unique_find_reservations (
  id bigint generated by default as identity primary key,
  customer_id bigint NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
  cart_id bigint NOT NULL REFERENCES carts(id) ON DELETE CASCADE,
  product_id bigint NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  variant_id bigint NOT NULL REFERENCES product_variants(id) ON DELETE CASCADE,
  quantity bigint NOT NULL DEFAULT 1 CHECK (quantity = 1),
  status text NOT NULL DEFAULT 'active' CHECK (status IN ('active','released','converted','expired')),
  expires_at bigint NOT NULL,
  idempotency_key text NOT NULL UNIQUE,
  created_at bigint NOT NULL DEFAULT (extract(epoch from now())::bigint),
  updated_at bigint NOT NULL DEFAULT (extract(epoch from now())::bigint)
);
CREATE UNIQUE INDEX IF NOT EXISTS unique_find_active_reservation_per_variant_customer
  ON unique_find_reservations(customer_id, variant_id) WHERE status = 'active';
CREATE INDEX IF NOT EXISTS unique_find_reservations_expiry_idx
  ON unique_find_reservations(status, expires_at);
