CREATE TABLE IF NOT EXISTS product_revisions (
  id bigint generated by default as identity primary key,
  product_id bigint NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  snapshot text NOT NULL,
  admin_email text NOT NULL,
  created_at bigint NOT NULL DEFAULT (extract(epoch from now())::bigint)
);

CREATE INDEX IF NOT EXISTS product_revisions_product_created_idx
  ON product_revisions(product_id, created_at DESC, id DESC);

ALTER TABLE public.product_revisions ENABLE ROW LEVEL SECURITY;
