create table if not exists public.email_contacts (
  id bigint generated by default as identity primary key,
  email text not null unique,
  first_source text not null default 'unknown',
  last_source text not null default 'unknown',
  first_seen_at bigint not null default extract(epoch from now())::bigint,
  last_seen_at bigint not null default extract(epoch from now())::bigint
);

create index if not exists email_contacts_last_seen_idx on public.email_contacts (last_seen_at desc);

insert into public.email_contacts (email, first_source, last_source)
select lower(trim(email)), 'newsletter', 'newsletter'
from public.newsletter_subscribers
where trim(email) <> ''
on conflict (email) do nothing;

insert into public.email_contacts (email, first_source, last_source)
select lower(trim(email)), 'account', 'account'
from public.customers
where trim(email) <> '' and email not like '%@members.invalid'
on conflict (email) do nothing;

alter table public.email_contacts enable row level security;
